common: &common
  adapter: postgresql
  username: kezz
  password: 

development:
  <<: *common
  database: kezz_development

test:
  <<: *common
  database: kezz_test

production:
  <<: *common
  database: kezz_production